owner: m-srl
repo: uptime-monitor

user-agent: Upptime-Pegasus-Monitor

sites:
  - name: Pegasus
    url: https://pegasusit.ro
    expectedStatusCodes:
      - 200

  - name: Pegasus - Health
    url: https://status.pegasusit.ro/health
    headers:
      - "X-Health-Token: $HEALTH_TOKEN"
    expectedStatusCodes:
      - 200
    maxResponseTime: 1000

  - name: Pegasus - Proprietati
    url: https://pegasusit.ro/proprietati
    expectedStatusCodes:
      - 200

status-website:
  cname: ""
  baseUrl: /uptime-monitor
  name: Uptime Status
  introTitle: "Status checks"
  introMessage: "Monitorizare automata a serviciilor."
  logoUrl: ""

notifications:
  - telegram:
      botToken: $NOTIFICATION_TELEGRAM_BOT_KEY
      chatId: $NOTIFICATION_TELEGRAM_CHAT_ID

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci]"
  graphsUpdate: ":bar_chart: Update graphs [skip ci]"
  readmeBuild: ":robot: Built README [skip ci]"

i18n:
  activeIncidents: Incidente active
  allSystemsOperational: Toate serviciile functioneaza corect
  incidentReportOn: Raport incident pe
  incident: Incident
  scheduledMaintenance: Mentenanta programata
  status: Status
  upptime: Generat de Upptime
  responseTime: Timp raspuns
  uptime: Uptime
  hours: ore
  days: zile
  months: luni
  years: ani
  ago: in urma
